### ISSUE TITLE
虽不出名，但绝对是一个好的侧滑解决方案！

### ISSUE THREAD

**Issue by TheFallStar** [ocyisheng/SYPopGesture#1]
非常感谢作者的无私以及毫无功利心的奉献。我觉得GitHub上很开源控件的星星都是刷出来或者宣传出来的，本身的控件功能非常有限，但还能几百星。。。应该说侧滑解决方案我找了将近2年，你这个是唯一可以融入我的框架并且能完美解决UIScrollView侧滑退出的问题。网上吹的最好的据说是百度很久以前做的一个，但经过尝试兼容非常受限，并不能完美解决所有的侧滑退出问题。膜拜~~~~~虽然只有10颗星，但确实很好！这是我在码云上挂的一个项目框架https://gitee.com/jaa/project.git，融入很多实测效果非常好的第三方，希望大神能够指点一下架构的思想和改进方向，给点建议就好。

**Comment by ocyisheng** [comment]
😓欢迎一起学习进步
